tag-template: "v$RESOLVED_VERSION"
name-template: "v$RESOLVED_VERSION"
autolabeler:
  - label: 'documentation'
    files:
      - 'docs/**'
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: ":boom: Breaking changes"
    label: "major"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Refactoring"
    label: "refactoring"
template: |
  ## What’s Changed

  $CHANGES
