name: pre-commit

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up pre-commit
        run: uv tool install pre-commit

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files
