preflow_kwargs:
  datastore: local
  metadata: local
  environment: conda
flow_kwargs:
  deployment_info:
    hook:
      name: project_name.pipeline.example.example_flow.hook
      args:
        - 1
      kwargs:
        b: 2
  tag: my_extra_tag
