name: Deploy docs to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_test:
    runs-on: ubuntu-latest
    name: Deploy docs to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          $CONDA/bin/python -m pip install --upgrade pip
          $CONDA/bin/python -m pip install -r requirements.txt

      - name: Deploy
        run: |
          git fetch origin gh-pages
          cd docs
          $CONDA/bin/mkdocs gh-deploy --clean

